# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
  mvc:
    servlet:
      path: /api

swagger-ui:
  path: /swagger-ui.html
  tags-sorter: alpha
  operations-sorter: alpha
api-docs:
  path: /v3/api-docs
group-configs:
  - group: 'default'
    paths-to-match: '/**'
    packages-to-scan: com.xuanxi.backend.controller

server:
  port: 8080